# Generated by Django 2.1 on 2019-09-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_value', models.FloatField()),
                ('total_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_type', models.FloatField(choices=[(1, 0.01), (2, 0.05), (3, 0.1), (4, 0.25), (5, 1)])),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='change.Change')),
            ],
        ),
    ]
