# Generated by Django 2.1 on 2019-09-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('change', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_type',
            field=models.SmallIntegerField(choices=[(1, 0.01), (2, 0.05), (3, 0.1), (4, 0.25), (5, 1)]),
        ),
    ]
